# Generated by Django 4.2.6 on 2023-10-18 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Precio_kw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('duracion_m', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kw_media_producidos', models.FloatField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('duracion_m', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vecino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('porcentaje', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kw_media_consumidos', models.FloatField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('duracion_m', models.IntegerField()),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dss.vecino')),
            ],
        ),
    ]
